version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_USER=developer
      - POSTGRES_DB=Bridgenext-demo
    ports:
      - "5432:5432"
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
       - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Password1234
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password1234
      ME_CONFIG_MONGODB_URL: mongodb://developer:Password1234@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=developer
      - MINIO_ROOT_PASSWORD=Password1234
      - MINIO_DEFAULT_BUCKETS=bridgenext
    command: server /data --console-address ":9001"

volumes:
  minio-data: 
